#!/bin/bash -e

printenv
exit 0

#BUILD_PHP_VERSIONS="7.0 7.1 7.2 7.3"
BUILD_PHP_VERSIONS="7.0"

for php_version in ${BUILD_PHP_VERSIONS}; do
  if [ a"${CACHE_TAG}" == "alatest" ]; then
    IMAGE_FINAL_NAME=${DOCKER_REPO}:${php_version}
  else
    IMAGE_FINAL_NAME=${DOCKER_REPO}:${php_version}-${CACHE_TAG}
  fi

  echo "=> Building image ${IMAGE_FINAL_NAME} ..."
  docker build --build-arg php_version=${php_version} -f ${DOCKERFILE_PATH} -t ${IMAGE_FINAL_NAME} .
done
