#!/bin/bash -e

#BUILD_PHP_VERSIONS="7.0 7.1 7.2 7.3"
BUILD_PHP_VERSIONS="7.2"

for php_version in ${BUILD_PHP_VERSIONS}; do
  IMAGE_FINAL_NAME=`echo "${DOCKER_REPO}:${php_version}-${DOCKER_TAG}" | sed "s/-latest//g"`

  echo "=> Pushing image ${IMAGE_FINAL_NAME} ..."
  docker push ${IMAGE_FINAL_NAME}
done
